# -*- mode: salt -*-
{% set basedir = "/srv/data/schroot" %}
debootstrap:
  basedir: {{ basedir }}
  vendor:
    debian:
      repositories:
        default: http://deb.debian.org/debian
        security: http://security.debian.org

    ubuntu:
      repositories:
        default: http://archive.ubuntu.com/ubuntu

sbuild:
  basedir: {{ basedir }}
  chroots:
    sid:
      vendor: debian
      dist: sid
      architectures:
        - amd64
        - i386
      components:
        - main
        - contrib
        - non-free
      extra_dists:
        - experimental

    stretch:
      vendor: debian
      dist: stretch
      architectures:
        - amd64
      components:
        - main
        - contrib
        - non-free

    buster:
      vendor: debian
      dist: buster
      architectures:
        - amd64
        - i386
      components:
        - main
        - contrib
        - non-free
