docker:
  install_pypi_pip: false
  install_docker_py: true
  use_upstream_repo: false

  daemon_config:
    init: true

  compose_version: '1.26.2'
  pkg:
    name: docker.io
    allow_updates: true
