docker:
  use_upstream_repo: {{ stack.get('docker', {}).get('use_upstream_repo', None) | default(true) }}

  {% if __grains__['os'] == 'Ubuntu' %}
  repo:
    version: disco
  {% endif %}

  pkg:
    name: docker-ce
    allow_updates: true
