version: "3.7"

services:
  traefik:
    build: traefik.docker
    image: traefik:local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./traefik_dynamic_conf.toml:/etc/traefik/traefik_dynamic_conf.toml
      - ./certs:/certs
    ports:
      - "127.0.0.1:${TRAEFIK_PORT_HTTP:-80}:80"
      - "::1:${TRAEFIK_PORT_HTTP:-80}:80"
      - "127.0.0.1:${TRAEFIK_PORT_HTTPS:-443}:443"
      - "::1:${TRAEFIK_PORT_HTTPS:-443}:443"
      - "127.0.0.1:${TRAEFIK_PORT_DASHBOARD:-8080}:8080"
      - "::1:${TRAEFIK_PORT_DASHBOARD:-8080}:8080"
      - "127.0.0.1:${TRAEFIK_PORT_SSH:-8022}:22"
      - "::1:${TRAEFIK_PORT_SSH:-8022}:22"
    container_name: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.d.test`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web,web-secure"
      - "traefik.http.routers.api.middlewares=redirect-to-https@file"

  whoami:
    image: containous/whoami:latest
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=web,web-secure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.d.test`)"
      - "traefik.http.routers.whoami.middlewares=redirect-to-https@file"

networks:
  default:
    external:
      name: traefik
