version: "3.7"

services:
  consul:
    image: consul
    container_name: consul
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600/udp
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"
      - "traefik.http.routers.consul.rule=Host(`consul.d.test`)"
      - "traefik.http.routers.consul.entrypoints=web,web-secure"
      - "traefik.http.routers.consul.middlewares=redirect-to-https@file"
    volumes:
      - ./consul.json:/etc/consul.d/server.json:ro
      - ./consul-entrypoint.sh:/consul-entrypoint.sh:ro
    environment:
      - CONSUL_ADVERTISE_IP
      - CONSUL_ENCRYPT
    entrypoint: /consul-entrypoint.sh
    command: -node=consul -bootstrap-expect=3 -retry-join consul1 -retry-join consul2

  consul1:
    image: consul
    container_name: consul1
    volumes:
      - ./consul.json:/etc/consul.d/server.json:ro
      - ./consul-entrypoint.sh:/consul-entrypoint.sh:ro
    environment:
      - CONSUL_ENCRYPT
    entrypoint: /consul-entrypoint.sh
    command: -node=consul1 -retry-join consul -retry-join consul2 -bootstrap-expect=3

  consul2:
    image: consul
    container_name: consul2
    volumes:
      - ./consul.json:/etc/consul.d/server.json:ro
      - ./consul-entrypoint.sh:/consul-entrypoint.sh:ro
    environment:
      - CONSUL_ENCRYPT
    entrypoint: /consul-entrypoint.sh
    command: -node=consul2 -retry-join consul -retry-join consul1 -bootstrap-expect=3
