[global]
  insecureSNI = true

[serversTransport]
  insecureSkipVerify = true
  rootCAs = ["/certs/rootCA.pem"]

[api]
  insecure = true
  dashboard = true


[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"
    [entryPoints.web-secure.http.tls]

  [entryPoints.ssh]
    address = ":22"
  [entryPoints.ssh-alt]
    address = ":2222"

[http.middlewares]
  [http.middlewares.redirect.redirectScheme]
    scheme = "https"

[certificatesResolvers.pebble.acme]
  email = "test@docker.localhost"
  storage = "/var/run/acme.json"
  caServer = "https://pebble:14000/dir"
  [certificatesResolvers.pebble.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"


[providers.docker]
  exposedByDefault = false

[providers.consulCatalog]
  exposedByDefault = false
  refreshInterval = "10s"
  [providers.consulCatalog.endpoint]
    address = "consul.node.consul:8500"

[log]
  level = "DEBUG"

[accesslog]

[providers]
  [providers.file]
    filename = "/etc/traefik/traefik_dynamic_conf.toml"
